"""Add new entities for complete FoodSphere implementation

Revision ID: 9efe7ce1340a
Revises: c9ea75111058
Create Date: 2025-10-24 21:13:38.511534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efe7ce1340a'
down_revision: Union[str, Sequence[str], None] = 'c9ea75111058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
