"""create vendor and item

Revision ID: c9ea75111058
Revises: f3a7561cd3e5
Create Date: 2025-10-24 20:01:20.334101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ea75111058'
down_revision: Union[str, Sequence[str], None] = 'f3a7561cd3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_category_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('items_category_id_fkey'), 'items', 'item_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
